name: second-pipeline

on: push


jobs:
  BUILD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

        
      - name: Install java and maven
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'


      - name: Check java version     
      - run: java --version


      - name: Check maven version
      - run: maven --version


      - name: Build cmd
      - run: mvn clean package

      - name: Check artifact
      - run: ls -ltr /target

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1

        with:
          name: login-logout.jar
          path: target/*.jar

    
