name: My First CI Pipeline

<<<<<<< HEAD
<<<<<<< HEAD
on:
  pull_request:
    branches:
      - main
=======
on: workflow_dispatch
>>>>>>> a58586257522be7406da50f6e594975c7300604a
=======
on: workflow_dispatch
>>>>>>> a58586257522be7406da50f6e594975c7300604a

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
<<<<<<< HEAD
<<<<<<< HEAD
        run: echo "Pull Request pipeline is working"
=======
        run: echo "GitHub Actions is working"
>>>>>>> a58586257522be7406da50f6e594975c7300604a
=======
        run: echo "GitHub Actions is working"
>>>>>>> a58586257522be7406da50f6e594975c7300604a
